### ISSUE TITLE
Stream getters for `tmp::file`

### ISSUE THREAD

**Issue by bugdea1er** [bugdea1er/tmp#99]
Since `tmp::file` encapsulates write-mode logic, it would be nice to have methods for getting both input and output streams:
```
/// Returns the input stream to this file
std::ifstream input_stream() const;

/// Returns the output stream to this file
std::ofstream output_stream(bool append = false) const;
```

**Comment by bgs99** [comment]
I would suggest using https://en.cppreference.com/w/cpp/io/ios_base/openmode instead of the boolean flag
